---
functional:
  - Сайт должен иметь мобильную версию.
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
  - Сайт должен быть доступен на различных устройствах.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
implicit:
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - В функции выбор категории нельзя выбрать все товары, после какой-то выбраной категории.
  - При добавление товара в корзину нельзя выбрать количество товаров.
  - На сайте нет регистрации и авторизации пользователя.
  - При оформлении заказа неизвестно как связаться с пользователем.
  - При выборе товаров в корзину не меняется оставшееся количество оставшегося товара.
  - При переводе сайта на русский язык, не переводится описание товара.
  - В корзине при удалении товара, нет модального окна для подтверждения об удалении товара.
  - При оформлении заказа нет кнопки "подтвердить заказ". 
